// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CardItem: typeof import('./src/components/cards/CardItem.vue')['default']
    CardsStack: typeof import('./src/components/cards/CardsStack.vue')['default']
    Main: typeof import('./src/components/pages/Main.vue')['default']
  }
}

export { }
